### ISSUE TITLE
Add BSD-like license so that rasa doesn't have a hard time with licensing.

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/yi-rope#10]
As just four people touched the code according to git log, I imagine that this is actually feasible.

@jhance 
@Fuuzetsu 
@siddhanathan 

Please express your consent or the lack of it.

**Comment by jyp** [comment]
Not sure if this is relevant to the case, but i refuse to have my
contributions downgraded to BSD.

Cheers,
-- JP

sent from my phone.

On 26 Jan 2017 17:38, "Dmitry Ivanov" <notifications@github.com> wrote:

As just four people touched the code according to git log, I imagine that
this is actually feasible.

@jhance <https://github.com/jhance>
@Fuuzetsu <https://github.com/Fuuzetsu>
@siddhanathan <https://github.com/siddhanathan>

Please express your consent or the lack of it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yi-editor/yi-rope/issues/10>, or mute the thread

**Comment by ethercrow** [comment]
@jyp Could you review this repo to be more sure about the amount of your contributions here?

**Comment by siddhanathan** [comment]
I would prefer LGPL over BSD, if the need arises. But that being said, my contributions to this package are small, so I don't care - I'm okay with it if everyone else agrees.

**Comment by noughtmare** [comment]
The authors of rasa are also rethinking their choice of license, see https://github.com/ChrisPenner/rasa/issues/34.

**Comment by jyp** [comment]
As I see it the design has not changed significantly from what Gustav Munkby and I put together back in the days. The similarity is obvious if you compare https://github.com/yi-editor/yi-rope/commit/de9173892dd4b47fc8fb4594c5345ed4f4d7b45f and the current https://github.com/yi-editor/yi-rope/blob/master/src/Yi/Rope.hs So as far as I'm concerned this request is a no-go. (It was actually a mistake to take away the copyright notice at the top of the file, I'd appreciate if it were put back, or if original authors were otherwise properly acknowledged).

**Comment by ChrisPenner** [comment]
I appreciate the conversation! As per @siddhanathan 's comment in the other thread; would it be agreeable to alter `yi-rope`'s license to `GPLv2 or later` or something similar? Then Rasa would be licensed as `GPLv3`.

**Comment by jgeerds** [comment]
Here is the relevant link: https://www.gnu.org/licenses/gpl-faq.en.html#v2v3Compatibility

So it would really help if `yi-rope` would change its license to `GPL “version 2 or later”`

**Comment by jyp** [comment]
My contributions are licensed under GPL version 2 or later.

**Comment by siddhanathan** [comment]
I just realized GPLv2 on cabal implies v2 or later. So rasa should have no issues with licensing.

I think we should add a separate authors file for this repo so that we can keep track of the copyrights. And we could mention the original authors in that file, the same way we mention the original authors in the main repo.

**Comment by jyp** [comment]
Sounds good to me. It looks like we can resolve this matter to everyone satisfaction.

**Comment by Fuuzetsu** [comment]
GPLv2+ is fine; I think we could argue that the contribution from original code left over is small/minimal: beyond naming, pretty much everything was changed. But we're happy with GPLv2+ so let's not argue.

**Comment by ethercrow** [comment]
All right, thank you everyone.

**Comment by jyp** [comment]
> I think we could argue that the contribution from original code left over
is small/minimal

For the record, I fully disagree with this statement. Please see my
assessment above.

**Comment by Fuuzetsu** [comment]
Of course there's a similarity, both are just fingertrees over some chunks. AFAIU the main selling point of old idea was that the chunks were UTF8-encoded ByteStrings; other than the idea of using chunks in fingertree, everything else was written, benchmarked and tested from scratch (though obviously there are "obvious" ways to do things) and actually this is where copyright notice was lost, when I started an new file and didn't transfer it.

Of course I'd be straight-up lying if I said it had nothing to do with yours and Gustav's *idea* and want to give attribution but do I insert copyright from 2008 on code that uses a couple of lines from old one but otherwise didn't exist until few years ago? Or perhaps write a notice with attribution?

I'm just unsure; let me know what you'd like and I'll be happy to (re-)add it.

**Comment by jyp** [comment]
I've taken a thorough look at the version that I last touched, https://github.com/yi-editor/yi/blob/8385b2f1fe82e275939b827152db4d783a934968/src/Data/Rope.hs (git-blame mostly credits me and Gustav on this one). The data structures and critical algorithms (split, append) are essentially unchanged in the current version. I can only conclude that the current code definitely remains tainted by my and Gustav's copyright. To say that the current code only uses "a couple of lines" of the old version is. (Not to minimize your contribution; the quality of the code has definitely improved.)

Please credit Gustav and me in the way you feel most appropriate (in an AUTHORS file as was suggested by @siddhanathan would be great).

**Comment by Fuuzetsu** [comment]
I have now added an AUTHORS file. I hope that's satisfactory!

**Comment by jyp** [comment]
Thank you for this! :+1:

On Tue, Jan 31, 2017 at 2:07 PM, Mateusz Kowalczyk <notifications@github.com
